# Generated by Django 3.2.9 on 2021-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_news', models.CharField(max_length=100)),
                ('detail_news', models.TextField()),
                ('photo_news', models.ImageField(default='', upload_to='photo')),
                ('date_news', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
